spring.application.name=Subscription Billing Simulator
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=filesystem:src/main/resources/db/migration
logging.level.org.flywaydb=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/sub_billing
spring.datasource.username=postgres
spring.datasource.password=postgres